version: 2

jobs:
  build:
    docker:
      - image: circleci/node:11

    working_directory: ~/giphy-search

    steps:
      - checkout
      - run: yarn
      - run: yarn test
      - run: yarn build
