version: 2

jobs:
  build:
    docker:
      - image: circleci/node:11

    working_directory: ~/giphy-search

    steps:
      - checkout
      - run:
          name: npm-install-yarn
          command: "sudo npm install -g yarn"
      - run:
          name: yarn-install
          command: "yarn install"
      - run:
          name: yarn-test
          command: "yarn test"
      - run:
          name: yarn-build
          command: "yarn build"
